package syncinfo.model;

import java.io.Serializable;

public class Role implements Serializable {
	public Role(String roleid, String rolename, String rolecode, Short sortorder, String description) {
		super();
		this.roleid = roleid;
		this.rolename = rolename;
		this.rolecode = rolecode;
		this.sortorder = sortorder;
		this.description = description;
	}

	public Role() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_ROLE.ROLEID
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_ROLE.ROLENAME
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_ROLE.ROLECODE
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_ROLE.SORTORDER
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    private Short sortorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_ROLE.DESCRIPTION
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_ROLE.ROLEID
     *
     * @return the value of DB2ADMIN.TC_ROLE.ROLEID
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_ROLE.ROLEID
     *
     * @param roleid the value for DB2ADMIN.TC_ROLE.ROLEID
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_ROLE.ROLENAME
     *
     * @return the value of DB2ADMIN.TC_ROLE.ROLENAME
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_ROLE.ROLENAME
     *
     * @param rolename the value for DB2ADMIN.TC_ROLE.ROLENAME
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_ROLE.ROLECODE
     *
     * @return the value of DB2ADMIN.TC_ROLE.ROLECODE
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_ROLE.ROLECODE
     *
     * @param rolecode the value for DB2ADMIN.TC_ROLE.ROLECODE
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_ROLE.SORTORDER
     *
     * @return the value of DB2ADMIN.TC_ROLE.SORTORDER
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public Short getSortorder() {
        return sortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_ROLE.SORTORDER
     *
     * @param sortorder the value for DB2ADMIN.TC_ROLE.SORTORDER
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public void setSortorder(Short sortorder) {
        this.sortorder = sortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_ROLE.DESCRIPTION
     *
     * @return the value of DB2ADMIN.TC_ROLE.DESCRIPTION
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_ROLE.DESCRIPTION
     *
     * @param description the value for DB2ADMIN.TC_ROLE.DESCRIPTION
     *
     * @mbggenerated Sun Aug 16 13:22:56 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}
