package syncinfo.model;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysLogExample {
	
	private int startRow;
	private int endRow;    
	public int getPageSize(){
		return endRow-startRow+1;
	}
	public int getPageStart(){
		return startRow-1;
	}
    public int getStartRow() {
		return startRow;
	}

	public void setStartRow(int startRow) {
		this.startRow = startRow;
	}

	public int getEndRow() {
		return endRow;
	}

	public void setEndRow(int endRow) {
		this.endRow = endRow;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public SysLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }
        public Criteria andOperationtypeLike(String value) {
            addCriterion("OPERATIONTYPE like", value, "operationtype");
            return (Criteria) this;
        }
        public Criteria andCeatedateGreaterThanOrEqualTo(Timestamp createdate) {
            addCriterion("CREATEDATE >=", createdate, "createdate");
            return (Criteria) this;
        }

        public Criteria andCeatedateLessThanOrEqualTo(Timestamp createdate2) {
            addCriterion("CREATEDATE <=", createdate2, "createdate");
            return (Criteria) this;
        }
        public Criteria andOperationcertsnIsNull() {
            addCriterion("OPERATIONCERTSN is null");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnIsNotNull() {
            addCriterion("OPERATIONCERTSN is not null");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnEqualTo(String value) {
            addCriterion("OPERATIONCERTSN =", value, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnNotEqualTo(String value) {
            addCriterion("OPERATIONCERTSN <>", value, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnGreaterThan(String value) {
            addCriterion("OPERATIONCERTSN >", value, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATIONCERTSN >=", value, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnLessThan(String value) {
            addCriterion("OPERATIONCERTSN <", value, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnLessThanOrEqualTo(String value) {
            addCriterion("OPERATIONCERTSN <=", value, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnLike(String value) {
            addCriterion("OPERATIONCERTSN like", value, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnNotLike(String value) {
            addCriterion("OPERATIONCERTSN not like", value, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnIn(List<String> values) {
            addCriterion("OPERATIONCERTSN in", values, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnNotIn(List<String> values) {
            addCriterion("OPERATIONCERTSN not in", values, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnBetween(String value1, String value2) {
            addCriterion("OPERATIONCERTSN between", value1, value2, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andOperationcertsnNotBetween(String value1, String value2) {
            addCriterion("OPERATIONCERTSN not between", value1, value2, "operationcertsn");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andCertidIsNull() {
            addCriterion("CERTID is null");
            return (Criteria) this;
        }

        public Criteria andCertidIsNotNull() {
            addCriterion("CERTID is not null");
            return (Criteria) this;
        }

        public Criteria andCertidEqualTo(BigDecimal value) {
            addCriterion("CERTID =", value, "certid");
            return (Criteria) this;
        }

        public Criteria andCertidNotEqualTo(BigDecimal value) {
            addCriterion("CERTID <>", value, "certid");
            return (Criteria) this;
        }

        public Criteria andCertidGreaterThan(BigDecimal value) {
            addCriterion("CERTID >", value, "certid");
            return (Criteria) this;
        }

        public Criteria andCertidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CERTID >=", value, "certid");
            return (Criteria) this;
        }

        public Criteria andCertidLessThan(BigDecimal value) {
            addCriterion("CERTID <", value, "certid");
            return (Criteria) this;
        }

        public Criteria andCertidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CERTID <=", value, "certid");
            return (Criteria) this;
        }

        public Criteria andCertidIn(List<BigDecimal> values) {
            addCriterion("CERTID in", values, "certid");
            return (Criteria) this;
        }

        public Criteria andCertidNotIn(List<BigDecimal> values) {
            addCriterion("CERTID not in", values, "certid");
            return (Criteria) this;
        }

        public Criteria andCertidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CERTID between", value1, value2, "certid");
            return (Criteria) this;
        }

        public Criteria andCertidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CERTID not between", value1, value2, "certid");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andLogtypeIsNull() {
            addCriterion("LOGTYPE is null");
            return (Criteria) this;
        }

        public Criteria andLogtypeIsNotNull() {
            addCriterion("LOGTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andLogtypeEqualTo(Short value) {
            addCriterion("LOGTYPE =", value, "logtype");
            return (Criteria) this;
        }

        public Criteria andLogtypeNotEqualTo(Short value) {
            addCriterion("LOGTYPE <>", value, "logtype");
            return (Criteria) this;
        }

        public Criteria andLogtypeGreaterThan(Short value) {
            addCriterion("LOGTYPE >", value, "logtype");
            return (Criteria) this;
        }

        public Criteria andLogtypeGreaterThanOrEqualTo(Short value) {
            addCriterion("LOGTYPE >=", value, "logtype");
            return (Criteria) this;
        }

        public Criteria andLogtypeLessThan(Short value) {
            addCriterion("LOGTYPE <", value, "logtype");
            return (Criteria) this;
        }

        public Criteria andLogtypeLessThanOrEqualTo(Short value) {
            addCriterion("LOGTYPE <=", value, "logtype");
            return (Criteria) this;
        }

        public Criteria andLogtypeIn(List<Short> values) {
            addCriterion("LOGTYPE in", values, "logtype");
            return (Criteria) this;
        }

        public Criteria andLogtypeNotIn(List<Short> values) {
            addCriterion("LOGTYPE not in", values, "logtype");
            return (Criteria) this;
        }

        public Criteria andLogtypeBetween(Short value1, Short value2) {
            addCriterion("LOGTYPE between", value1, value2, "logtype");
            return (Criteria) this;
        }

        public Criteria andLogtypeNotBetween(Short value1, Short value2) {
            addCriterion("LOGTYPE not between", value1, value2, "logtype");
            return (Criteria) this;
        }

        public Criteria andApplytypeIsNull() {
            addCriterion("APPLYTYPE is null");
            return (Criteria) this;
        }

        public Criteria andApplytypeIsNotNull() {
            addCriterion("APPLYTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andApplytypeEqualTo(Short value) {
            addCriterion("APPLYTYPE =", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeNotEqualTo(Short value) {
            addCriterion("APPLYTYPE <>", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeGreaterThan(Short value) {
            addCriterion("APPLYTYPE >", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeGreaterThanOrEqualTo(Short value) {
            addCriterion("APPLYTYPE >=", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeLessThan(Short value) {
            addCriterion("APPLYTYPE <", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeLessThanOrEqualTo(Short value) {
            addCriterion("APPLYTYPE <=", value, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeIn(List<Short> values) {
            addCriterion("APPLYTYPE in", values, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeNotIn(List<Short> values) {
            addCriterion("APPLYTYPE not in", values, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeBetween(Short value1, Short value2) {
            addCriterion("APPLYTYPE between", value1, value2, "applytype");
            return (Criteria) this;
        }

        public Criteria andApplytypeNotBetween(Short value1, Short value2) {
            addCriterion("APPLYTYPE not between", value1, value2, "applytype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeIsNull() {
            addCriterion("OPERATIONTYPE is null");
            return (Criteria) this;
        }

        public Criteria andOperationtypeIsNotNull() {
            addCriterion("OPERATIONTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOperationtypeEqualTo(Short value) {
            addCriterion("OPERATIONTYPE =", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeNotEqualTo(Short value) {
            addCriterion("OPERATIONTYPE <>", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeGreaterThan(Short value) {
            addCriterion("OPERATIONTYPE >", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeGreaterThanOrEqualTo(Short value) {
            addCriterion("OPERATIONTYPE >=", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeLessThan(Short value) {
            addCriterion("OPERATIONTYPE <", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeLessThanOrEqualTo(Short value) {
            addCriterion("OPERATIONTYPE <=", value, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeIn(List<Short> values) {
            addCriterion("OPERATIONTYPE in", values, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeNotIn(List<Short> values) {
            addCriterion("OPERATIONTYPE not in", values, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeBetween(Short value1, Short value2) {
            addCriterion("OPERATIONTYPE between", value1, value2, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOperationtypeNotBetween(Short value1, Short value2) {
            addCriterion("OPERATIONTYPE not between", value1, value2, "operationtype");
            return (Criteria) this;
        }

        public Criteria andOsIsNull() {
            addCriterion("OS is null");
            return (Criteria) this;
        }

        public Criteria andOsIsNotNull() {
            addCriterion("OS is not null");
            return (Criteria) this;
        }

        public Criteria andOsEqualTo(String value) {
            addCriterion("OS =", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotEqualTo(String value) {
            addCriterion("OS <>", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThan(String value) {
            addCriterion("OS >", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThanOrEqualTo(String value) {
            addCriterion("OS >=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThan(String value) {
            addCriterion("OS <", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThanOrEqualTo(String value) {
            addCriterion("OS <=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLike(String value) {
            addCriterion("OS like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotLike(String value) {
            addCriterion("OS not like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsIn(List<String> values) {
            addCriterion("OS in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotIn(List<String> values) {
            addCriterion("OS not in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsBetween(String value1, String value2) {
            addCriterion("OS between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotBetween(String value1, String value2) {
            addCriterion("OS not between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andBrowserIsNull() {
            addCriterion("BROWSER is null");
            return (Criteria) this;
        }

        public Criteria andBrowserIsNotNull() {
            addCriterion("BROWSER is not null");
            return (Criteria) this;
        }

        public Criteria andBrowserEqualTo(String value) {
            addCriterion("BROWSER =", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserNotEqualTo(String value) {
            addCriterion("BROWSER <>", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserGreaterThan(String value) {
            addCriterion("BROWSER >", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserGreaterThanOrEqualTo(String value) {
            addCriterion("BROWSER >=", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserLessThan(String value) {
            addCriterion("BROWSER <", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserLessThanOrEqualTo(String value) {
            addCriterion("BROWSER <=", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserLike(String value) {
            addCriterion("BROWSER like", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserNotLike(String value) {
            addCriterion("BROWSER not like", value, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserIn(List<String> values) {
            addCriterion("BROWSER in", values, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserNotIn(List<String> values) {
            addCriterion("BROWSER not in", values, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserBetween(String value1, String value2) {
            addCriterion("BROWSER between", value1, value2, "browser");
            return (Criteria) this;
        }

        public Criteria andBrowserNotBetween(String value1, String value2) {
            addCriterion("BROWSER not between", value1, value2, "browser");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("IP is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("IP is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("IP =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("IP <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("IP >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("IP >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("IP <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("IP <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("IP like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("IP not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("IP in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("IP not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("IP between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("IP not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andExecutetimeIsNull() {
            addCriterion("EXECUTETIME is null");
            return (Criteria) this;
        }

        public Criteria andExecutetimeIsNotNull() {
            addCriterion("EXECUTETIME is not null");
            return (Criteria) this;
        }

        public Criteria andExecutetimeEqualTo(String value) {
            addCriterion("EXECUTETIME =", value, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeNotEqualTo(String value) {
            addCriterion("EXECUTETIME <>", value, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeGreaterThan(String value) {
            addCriterion("EXECUTETIME >", value, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeGreaterThanOrEqualTo(String value) {
            addCriterion("EXECUTETIME >=", value, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeLessThan(String value) {
            addCriterion("EXECUTETIME <", value, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeLessThanOrEqualTo(String value) {
            addCriterion("EXECUTETIME <=", value, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeLike(String value) {
            addCriterion("EXECUTETIME like", value, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeNotLike(String value) {
            addCriterion("EXECUTETIME not like", value, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeIn(List<String> values) {
            addCriterion("EXECUTETIME in", values, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeNotIn(List<String> values) {
            addCriterion("EXECUTETIME not in", values, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeBetween(String value1, String value2) {
            addCriterion("EXECUTETIME between", value1, value2, "executetime");
            return (Criteria) this;
        }

        public Criteria andExecutetimeNotBetween(String value1, String value2) {
            addCriterion("EXECUTETIME not between", value1, value2, "executetime");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andRequestparamIsNull() {
            addCriterion("REQUESTPARAM is null");
            return (Criteria) this;
        }

        public Criteria andRequestparamIsNotNull() {
            addCriterion("REQUESTPARAM is not null");
            return (Criteria) this;
        }

        public Criteria andRequestparamEqualTo(String value) {
            addCriterion("REQUESTPARAM =", value, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamNotEqualTo(String value) {
            addCriterion("REQUESTPARAM <>", value, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamGreaterThan(String value) {
            addCriterion("REQUESTPARAM >", value, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamGreaterThanOrEqualTo(String value) {
            addCriterion("REQUESTPARAM >=", value, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamLessThan(String value) {
            addCriterion("REQUESTPARAM <", value, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamLessThanOrEqualTo(String value) {
            addCriterion("REQUESTPARAM <=", value, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamLike(String value) {
            addCriterion("REQUESTPARAM like", value, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamNotLike(String value) {
            addCriterion("REQUESTPARAM not like", value, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamIn(List<String> values) {
            addCriterion("REQUESTPARAM in", values, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamNotIn(List<String> values) {
            addCriterion("REQUESTPARAM not in", values, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamBetween(String value1, String value2) {
            addCriterion("REQUESTPARAM between", value1, value2, "requestparam");
            return (Criteria) this;
        }

        public Criteria andRequestparamNotBetween(String value1, String value2) {
            addCriterion("REQUESTPARAM not between", value1, value2, "requestparam");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 24 11:35:58 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DB2ADMIN.TC_LOG
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}