package syncinfo.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import org.apache.shiro.SecurityUtils;

import syncinfo.utils.DateUtils;
import syncinfo.utils.OSUtil;

public class SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.ID
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.OPERATIONCERTSN
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private String operationcertsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.USERID
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.CERTID
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private BigDecimal certid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.CREATEDATE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.LOGTYPE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private BigDecimal logtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.APPLYTYPE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private BigDecimal applytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.OPERATIONTYPE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private String operationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.OS
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.BROWSER
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private String browser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.IP
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.EXECUTETIME
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private String executetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.DESCRIPTION
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.TC_LOG.REQUESTPARAM
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    private String requestparam;
    
    private BigDecimal logresult;
    

    public BigDecimal getLogresult() {
		return logresult;
	}

	public void setLogresult(BigDecimal logresult) {
		this.logresult = logresult;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.ID
     *
     * @return the value of DB2ADMIN.TC_LOG.ID
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.ID
     *
     * @param id the value for DB2ADMIN.TC_LOG.ID
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.OPERATIONCERTSN
     *
     * @return the value of DB2ADMIN.TC_LOG.OPERATIONCERTSN
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getOperationcertsn() {
        return operationcertsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.OPERATIONCERTSN
     *
     * @param operationcertsn the value for DB2ADMIN.TC_LOG.OPERATIONCERTSN
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setOperationcertsn(String operationcertsn) {
        this.operationcertsn = operationcertsn == null ? null : operationcertsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.USERID
     *
     * @return the value of DB2ADMIN.TC_LOG.USERID
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.USERID
     *
     * @param userid the value for DB2ADMIN.TC_LOG.USERID
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.CERTID
     *
     * @return the value of DB2ADMIN.TC_LOG.CERTID
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public BigDecimal getCertid() {
        return certid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.CERTID
     *
     * @param certid the value for DB2ADMIN.TC_LOG.CERTID
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setCertid(BigDecimal certid) {
        this.certid = certid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.CREATEDATE
     *
     * @return the value of DB2ADMIN.TC_LOG.CREATEDATE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.CREATEDATE
     *
     * @param createdate the value for DB2ADMIN.TC_LOG.CREATEDATE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.LOGTYPE
     *
     * @return the value of DB2ADMIN.TC_LOG.LOGTYPE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public BigDecimal getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.LOGTYPE
     *
     * @param logtype the value for DB2ADMIN.TC_LOG.LOGTYPE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setLogtype(BigDecimal logtype) {
        this.logtype = logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.APPLYTYPE
     *
     * @return the value of DB2ADMIN.TC_LOG.APPLYTYPE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public BigDecimal getApplytype() {
        return applytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.APPLYTYPE
     *
     * @param applytype the value for DB2ADMIN.TC_LOG.APPLYTYPE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setApplytype(BigDecimal applytype) {
        this.applytype = applytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.OPERATIONTYPE
     *
     * @return the value of DB2ADMIN.TC_LOG.OPERATIONTYPE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getOperationtype() {
        return operationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.OPERATIONTYPE
     *
     * @param operationtype the value for DB2ADMIN.TC_LOG.OPERATIONTYPE
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setOperationtype(String operationtype) {
        this.operationtype = operationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.OS
     *
     * @return the value of DB2ADMIN.TC_LOG.OS
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.OS
     *
     * @param os the value for DB2ADMIN.TC_LOG.OS
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.BROWSER
     *
     * @return the value of DB2ADMIN.TC_LOG.BROWSER
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.BROWSER
     *
     * @param browser the value for DB2ADMIN.TC_LOG.BROWSER
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.IP
     *
     * @return the value of DB2ADMIN.TC_LOG.IP
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.IP
     *
     * @param ip the value for DB2ADMIN.TC_LOG.IP
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.EXECUTETIME
     *
     * @return the value of DB2ADMIN.TC_LOG.EXECUTETIME
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getExecutetime() {
        return executetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.EXECUTETIME
     *
     * @param executetime the value for DB2ADMIN.TC_LOG.EXECUTETIME
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setExecutetime(String executetime) {
        this.executetime = executetime == null ? null : executetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.DESCRIPTION
     *
     * @return the value of DB2ADMIN.TC_LOG.DESCRIPTION
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.DESCRIPTION
     *
     * @param description the value for DB2ADMIN.TC_LOG.DESCRIPTION
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.TC_LOG.REQUESTPARAM
     *
     * @return the value of DB2ADMIN.TC_LOG.REQUESTPARAM
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public String getRequestparam() {
        return requestparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.TC_LOG.REQUESTPARAM
     *
     * @param requestparam the value for DB2ADMIN.TC_LOG.REQUESTPARAM
     *
     * @mbggenerated Mon Aug 24 11:35:58 CST 2015
     */
    public void setRequestparam(String requestparam) {
        this.requestparam = requestparam == null ? null : requestparam.trim().length()>128 ? requestparam.trim().substring(0,128) : requestparam.trim();
    }

	public SysLog() {
		super();
	}
    
	public SysLog(OSUtil osUtil) {
		super();
		Admin admin = (Admin) SecurityUtils.getSubject().getSession().getAttribute("admin");
		this.operationcertsn = admin.getAdminid();
		this.createdate = DateUtils.getSysTimestamp();
		this.operationtype = admin.getRolename();
		this.os = osUtil.getOSName();
		this.browser = osUtil.getExplorerName();
		this.ip = osUtil.getIp();
		this.executetime = osUtil.getExecuteTime();
	}
}